/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("RequestsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheRequestsList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheRequestsList.onFilterBar().iCheckFilterField("ID požadavku");
            Then.onTheRequestsList.onFilterBar().iCheckFilterField("Typ požadavku");
            Then.onTheRequestsList.onFilterBar().iCheckFilterField("Připojený systém");
            Then.onTheRequestsList.onFilterBar().iCheckFilterField("Status požadavku");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            // Then.ontheRequestsList.onTable().iPressDelete();
            Then.onTheRequestsList.onTable().iCheckDelete({ visible: true });
            // Then.onTheRequestsList.onTable().iPressAction("Create for System");
            Then.onTheRequestsList.onTable().iCheckAction("Create for System", { enabled: true });
            Then.onTheRequestsList.onTable().iCheckColumns(undefined, {"RequestId":{"header":"Request ID"},"RequestType":{"header":"Request Type"},"ExternalSystem":{"header":"External System"},"Status":{"header":"Status"},"CreatedBy":{"header":"Created By"},"PartnerGid":{"header":"Partner GID"},"Duns":{"header":"DUNS Number"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheRequestsList.onFilterBar().iExecuteSearch();
            
            Then.onTheRequestsList.onTable().iCheckRows();

            When.onTheRequestsList.onTable().iPressRow(0);
            Then.onTheRequestsObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});