/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("BusinessPartnerSearchListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheBusinessPartnerSearchList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheBusinessPartnerSearchList.onFilterBar().iCheckFilterField("Partner GID");
            Then.onTheBusinessPartnerSearchList.onFilterBar().iCheckFilterField("TaxNumber");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheBusinessPartnerSearchList.onTable().iCheckColumns(undefined, {"PartnerGID":{"header":"Partner GID"},"Country":{"header":"Klíč státu/regionu"},"TaxNumber":{"header":"TaxNumber"},"CompanyName":{"header":"Name Org"},"FirstName":{"header":"Jméno"},"LastName":{"header":"Příjmení"},"City":{"header":"Město"},"District":{"header":"Místní část"},"Street":{"header":"Ulice"},"HouseNo":{"header":"Číslo domu"},"HouseNoSuppl":{"header":"Dodatek"},"CityPostal":{"header":"PSČ"},"LeiCode":{"header":"LEI"},"Duns":{"header":"Číslo D-U-N-S"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheBusinessPartnerSearchList.onFilterBar().iExecuteSearch();
            
            Then.onTheBusinessPartnerSearchList.onTable().iCheckRows();

            When.onTheBusinessPartnerSearchList.onTable().iPressRow(0);
            Then.onTheBusinessPartnerSearchObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});