/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("RequestsObjectPageObjectPage journey");

        opaTest("Navigate to RequestsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheRequestsList.onFilterBar().iExecuteSearch();

            Then.onTheRequestsList.onTable().iCheckRows();
            When.onTheRequestsList.onTable().iPressRow(0);

            Then.onTheRequestsObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheRequestsObjectPage.iCheckNumberOfSections(5);
            When.onTheRequestsObjectPage.iPressSectionIconTabFilterButton("General");
            Then.onTheRequestsObjectPage.iCheckSection({ section: "General" });
            When.onTheRequestsObjectPage.iPressSectionIconTabFilterButton("CountrySpecificData");
            Then.onTheRequestsObjectPage.iCheckSection({ section: "CountrySpecificData" });
            Then.onTheRequestsObjectPage.onForm({ section: "CountrySpecificData" }).iCheckField({ property: "BusinessPartnerGroup" });
            Then.onTheRequestsObjectPage.onForm({ section: "CountrySpecificData" }).iCheckField({ property: "BusinessPartnerType" });
            Then.onTheRequestsObjectPage.onForm({ section: "CountrySpecificData" }).iCheckField({ property: "LegalForm" });
            Then.onTheRequestsObjectPage.onForm({ section: "CountrySpecificData" }).iCheckField({ property: "TelephoneNumber" });
            Then.onTheRequestsObjectPage.onForm({ section: "CountrySpecificData" }).iCheckField({ property: "MobileNumber" });
            Then.onTheRequestsObjectPage.onForm({ section: "CountrySpecificData" }).iCheckField({ property: "EmailAddress" });
            Then.onTheRequestsObjectPage.onForm({ section: "CountrySpecificData" }).iCheckField({ property: "Vendor" });
            Then.onTheRequestsObjectPage.onForm({ section: "CountrySpecificData" }).iCheckField({ property: "Customer" });
            Then.onTheRequestsObjectPage.onForm({ section: "CountrySpecificData" }).iCheckField({ property: "IsInactive" });
            Then.onTheRequestsObjectPage.onForm({ section: "CountrySpecificData" }).iCheckField({ property: "InactiveReason" });
            When.onTheRequestsObjectPage.iPressSectionIconTabFilterButton("Address");
            Then.onTheRequestsObjectPage.iCheckSection({ section: "Address" });
            Then.onTheRequestsObjectPage.onForm({ section: "Address" }).iCheckField({ property: "OrganizationName1" });
            Then.onTheRequestsObjectPage.onForm({ section: "Address" }).iCheckField({ property: "SearchTerm1" });
            Then.onTheRequestsObjectPage.onForm({ section: "Address" }).iCheckField({ property: "Country" });
            Then.onTheRequestsObjectPage.onForm({ section: "Address" }).iCheckField({ property: "District" });
            Then.onTheRequestsObjectPage.onForm({ section: "Address" }).iCheckField({ property: "City" });
            Then.onTheRequestsObjectPage.onForm({ section: "Address" }).iCheckField({ property: "PostalCode" });
            Then.onTheRequestsObjectPage.onForm({ section: "Address" }).iCheckField({ property: "Street" });
            Then.onTheRequestsObjectPage.onForm({ section: "Address" }).iCheckField({ property: "HouseNumber" });
            Then.onTheRequestsObjectPage.onForm({ section: "Address" }).iCheckField({ property: "HouseNumberSupplement" });
            When.onTheRequestsObjectPage.iPressSectionIconTabFilterButton("AddressVariants");
            Then.onTheRequestsObjectPage.iCheckSection({ section: "AddressVariants" });
            When.onTheRequestsObjectPage.iPressSectionIconTabFilterButton("TaxNumbers");
            Then.onTheRequestsObjectPage.iCheckSection({ section: "TaxNumbers" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});